<a href="https://colab.research.google.com/github/20Santiago/Para_tareas/blob/master/Tarea_del_d%C3%ADa_14_04_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Santiago Aguilar Cardenas**

**Tarea del día 14/04/2023**

In [1]:
#Lineas para usar Pandas en Colab
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
RUTA = '/content/drive/MyDrive/Principales_importadores.xlsx'

#Create data
db = pd.read_excel(RUTA)
display(db)

Mounted at /content/drive

,País,asociados,Año,Flujo comercial,N.o de productos comercializados a nivel de 6 dígitos del SA,exportación Proporción en el total de productos (%),exportación Valor del comercio (en miles de US$),exportación Proporción de asociados (%)
0,Mundo,Aruba,2020,Exportación,2639.0,57.25,763407.78,0.00
1,Mundo,Afghanistan,2020,Exportación,3211.0,69.65,6997392.68,0.04
2,Mundo,Angola,2020,Exportación,3807.0,82.58,7415780.55,0.04
3,Mundo,Anguila,2020,Exportación,1077.0,23.36,148554.23,0.00
4,Mundo,Albania,2020,Exportación,3799.0,82.41,5231256.75,0.03
...,...,...,...,...,...,...,...,...
243,Mundo,Yemen,2020,Exportación,3432.0,74.45,11108274.58,0.07
244,Mundo,South Africa,2020,Exportación,4424.0,95.97,69488184.16,0.41
245,Mundo,"Congo, Dem. Rep.",2020,Exportación,3754.0,81.43,6881514.78,0.04
246,Mundo,Zambia,2020,Exportación,3747.0,81.28,5200286.32,0.03
247,Mundo,Zimbabwe,2020,Exportación,3751.0,81.37,3921850.90,0.02

In [ ]:
# Recibir el nombre de una columna str y una númerica int
columna1 = input("Ingrese el nombre de la columna 1: ")
columna2 = input("Ingrese el nombre de la columna 2: ")



#Retornar valores únicos de la columna 1:
print(db[columna1].unique())



#Pedir al usuario un valor de la columna 1:
valor1 = input("Ingrese el valor de la columna 1: ")



#Guardar en A los datos numéricos sin los valores de esa columna numérica:
A = db[db[columna1] != valor1][columna2]



#Guardar en Y los datos de esa columna numérica:
Y = db[db[columna1] == valor1][columna2]



#Calcular el rango de la matriz A:
rango_A = np.linalg.matrix_rank(A)


#Verificar si la matriz A es invertible:
if rango_A < len(A):
    print("Como hay columnas linealmente independiente, la matriz A no es invertida.")
else:
  
#Resolver sistema de ecuaciones lineales AX = Y
    X = np.linalg.solve(A, Y)